### ISSUE TITLE
Config create on windows.

### ISSUE THREAD

**Issue by JosiahBradley** [bbkane/grabbit#1]
Executable does not make it clear how to create a new config and when attempting to run `.\grabbit.exe --edit-config -p .` only ` exec: "vim": executable file not found in %PATH%` is returned. Perhaps a default editor that is commonly found on each OS would work better here as well as default write location instead of .config in the home folder as windows normally uses a directory per application.

**Comment by JosiahBradley** [comment]
Using PowerShell I can set the missing EDITOR env var using `$env:EDITOR = 'notepad'` This would probably be best to just default to notepad as it is found in system32 in most users PATHs

**Comment by bbkane** [comment]
Agree haha

**Comment by bbkane** [comment]
I'll leave this open till I fix it

**Comment by bbkane** [comment]
can notepad handle '\n' for line endings? That's what the template string provides

**Comment by bbkane** [comment]
The new way to try to find an editor is:

- `--editor` flag
- `$EDITOR`
- A guess!!
