### ISSUE TITLE
Corrupted download.

### ISSUE THREAD

**Issue by JosiahBradley** [bbkane/grabbit#2]
This URL:
https://www.reddit.com/r/EarthPorn/comments/io729u/trying_to_capture_the_whole_beauty_of_the_bernina/
results in a 0 byte jpg downloading. This was reproducible after deleting and trying again.

**Comment by bbkane** [comment]
I tried to reproduce this by adding the following to `run`:

```
func run() error {

	downloadFile("https://i.redd.it/u1vf0mx55ql51.jpg", "tmp.jpg", true)
	return nil
```

**Comment by bbkane** [comment]
Guess I'll close this now...
