### ISSUE TITLE
Allow users to directly set wallpaper to location specified in config file.

### ISSUE THREAD

**Issue by JosiahBradley** [bbkane/grabbit#3]
Work in progress, assign to me. Allows users to provide a switch or top level command to set the wallpaper directory on their os.

**Comment by bbkane** [comment]
Something like this?

```
grabbit grab --set-wallpaper-dir ~/Pictures/grabbit
grabbit set-wallpaper-dir ~/Pictures/grabbit
```

**Comment by JosiahBradley** [comment]
More like

```
grabbit grab --set-wallpaper-dir [ -p path/to/myconfig.yaml ]
grabbit set-wallpaper-dir [ -p path/to/myconfig.yaml ]
```
This would pull the directory from `subreddits->destination` in the configuration file provided or default location. 
This approach is cleaner and doesn't abuse using this function as a general wallpaper setter.

**Comment by bbkane** [comment]
There can be multiple dirs in myconfig.yaml. Would it choose one?

**Comment by bbkane** [comment]
This turned out to be to difficult to be worth doing
