### ISSUE TITLE
Grabbit version empty on Windows.

### ISSUE THREAD

**Issue by JosiahBradley** [bbkane/grabbit#8]
```
(base) ~\Tools\grabbit\grabbit [master ≡ +3 ~0 -0 !]> .\grabbit.exe version
INFO: Version and build information
  builtBy: "devBuiltBy"
  commit: "devCommit"
  date: "devDate"
  version: "devVersion"
```

**Comment by bbkane** [comment]
In an attempt to reproduce this, I downloaded the latest version from https://github.com/bbkane/grabbit/releases/tag/v2.1.4 on Jenny's surface. I unzipped and untarred it with zip, and ran:

```
PS C:\Users\bbk15\Downloads> .\grabbit.exe version
INFO: Version and build information
  builtBy: "goreleaser"
  commit: "e0f6f5eb9313304b049861247ab403c9293d9af8"
  date: "2020-10-15T18:37:23Z"
  version: "2.1.4"
```

Perhaps you ran this on the version you cloned and built? This info is added by goreleaser

**Comment by bbkane** [comment]
Could you delete and redownload grabbit from the releases and see if this issue persists?

**Comment by JosiahBradley** [comment]
Built version that doesnt include gorealeser, this was in error.
